// Generated by IB v0.7.2 gem. Do not edit it manually
// Run `rake ib:open` to refresh

#import <UIKit/UIKit.h>
#import <Foundation/Foundation.h>
#import <CoreGraphics/CoreGraphics.h>

@interface AppDelegate: UIResponder <UIApplicationDelegate>
@end

@interface MainViewController: UIViewController

@property IBOutlet UIView * red_view;
@property IBOutlet UIView * blue_view;
@property IBOutlet UIView * green_view;

@end

